#!/bin/bash

function fetch_img {
	path="assets/img/yt-with-consent/$1.jpg"
	if [ ! -f "$path" ];
	then
	    echo "Fetching image for $1..."
	    curl -o "$path" "https://i.ytimg.com/vi/$1/maxresdefault.jpg"
	fi
}

if [ -z "$1" ];
then
	echo "Fetching all images..."
	for name in $(grep -roh "include youtube.html vid=\"[[:alnum:]_-]*\"" _plugins/ help/ index.html | awk '{print $3}' | awk -F= '{print $2}' | cut -d'"' -f 2)
	do
		fetch_img $name
	done
	echo "... done!"
else
	fetch_img $1;
fi
