exclude: ^(.*\.css|.*\.svg|_includes)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
  - repo: https://github.com/OctoPrint/codemods
    rev: devel
    hooks:
      - id: codemod_dict_to_literal
        stages: ["manual"]
      - id: codemod_set_to_literal
        stages: ["manual"]
      - id: codemod_not_in
        stages: ["manual"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.4
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: ["--config", "black.toml"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
