version: "3"

tasks:
  install:
    cmds:
      - |
        bundle install

  serve:
    cmds:
      - |
        bundle exec jekyll s --future
  
  assets:
    cmds:
      - |
        lessc "--clean-css=--s1 --advanced --compatibility=ie8" assets/less/site.less assets/css/site.css
  
  remove-plugin:
    desc: "Removes a plugin, use like this: task remove-plugin -- plugin_id"
    vars:
      PLUGIN: '{{.CLI_ARGS}}'
    cmds:
      - |
        echo "Removing plugin {{.PLUGIN}}..."
        [ -f "_plugins/{{.PLUGIN}}.md" ] && rm "_plugins/{{.PLUGIN}}.md" && echo "Deleted markdown @ _plugins/{{.PLUGIN}}.md"
        [ -d "assets/img/plugins/{{.PLUGIN}}" ] && rm -r "assets/img/plugins/{{.PLUGIN}}" && echo "Deleted assets @ assets/img/plugins/{{.PLUGIN}}"
        echo "... done!"
