name: Feature request
description: Use this to request new features for the plugin repository (NOT ANY PLUGINS!)
title: '[Feature Request] <insert short summary of request here>'
labels: 'enhancement'
body:
  - type: markdown
    attributes:
      value: >
        Use this to request new features **for the plugin repository**.


        Do **NOT** use this to request features for plugins registered in the repository,
        those should be filed with the plugin author. We can do nothing about it here.
  - type: textarea
    attributes:
      label: What do you want to see implemented in the plugin repository?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why, what problems would be solved by this?
      description: Please provide a few examples of the kind of problems that would be solved by implementing the feature request.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Any additional information you want to provide?
