name: Report suspicious plugin activity
about: Use this to report plugins that are doing something malicious and/or undocumented (e.g. crypto mining, suspicious network connections, unannounced tracking without opt-in, ...)
title: '[Suspicious Plugin Activity] <insert name of plugin here>'
labels: 'suspicious plugin activity'
issue_body: true
body:
  - type: markdown
    attributes:
      value: >
        You might come across a plugin that appears to be doing something suspicious that it shouldn't,
        like installing things on your system it doesn't need for its task, tracking without the
        possibility to opt-in, suspicious network connections to weird locations and so on.


        In such a case please first seek clarification of the issue with the plugin author by
        getting in touch with them e.g. on their plugin's issue tracker. If this isn't fruitful or
        you do not get any reply, fill out the form below and we'll investigate.
  - type: input
    attributes:
      label: Which Plugin?
      description: >-
        Please enter the URL to the **plugin page on the plugin repository** so there's no ambiguity!
      placeholder: https://plugins.octoprint.org/...
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What kind of suspicious activity are you reporting?
      options:
        - installing things on the system without my consent
        - tracking without opt-in
        - suspicious network activity
        - crypto mining
        - something else (specify below)
    validations:
      required: true
  - type: input
    attributes:
      label: If you selected "something else" above, what other kind of suspicious activity did you observe?
      description: >-
        Please note that things like bugs in the plugin, installation errors or missing
        features are **not** what qualifies as suspicious activity.
  - type: input
    attributes:
      label: Link to a ticket on the plugin's issue tracker about the problem
      description: >-
        The plugin author should be contacted first and asked to clarify the situation.
        Only proceed if this attempt at resolving the problem isn't fruitful or the author
        doesn't react.

        If there's no public issue tracker, some other form of proof should be provided
        here that the an attempt at a friendly resolution was actually made.
      placeholder: https://...
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        ### Further information you want to provide

        If there's any more information you want to provide, please do this here:
