name: Automatic PR Approval
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  automatic-approve:
    name: Automatic PR Approval
    runs-on: ubuntu-latest
    steps:
      - name: Automatic PR Approval
        uses: mheap/automatic-approve-action@v1.1.0
        with:
          token: ${{ secrets.metadata_token }}
          workflows: "pr-labeler.yml,validate-pull-requests.yml,publish-to-github-pages.yml"
          dangerous_files: ".github/scripts"
